#
# APPLICATION.PROPERTIES
# OracleDB with COGNOS UAT ENV
#

server:
  contextPath: /capitalreporting
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@dbRCRCH00.generali.it:1521:RCRCH
    username: GH_COGNOS_ASC001
    password: GH_COGNOS_ASC001
    driverClassName: oracle.jdbc.OracleDriver
  db:
    platform: oracle
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@dbRCRCH00.generali.it:1521:RCRCH
    username: GH_COGNOS_ASC001
    password: GH_COGNOS_ASC001
swagger:
  base-path: /capitalreporting
security:
  basic:
    enabled: true
    path: /api/**
  user:
    name: admin
    password: secret
cognos:
  bi:
    url: http://lghach15bic001.generali.it:9300/bi
