#
# APPLICATION.PROPERTIES
# In memory HSQLDB without COGNOS
#

server:
  contextPath: /capitalreporting
spring:
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    platform: hsqldb
swagger:
  base-path: /capitalreporting
cognos:
  bi:
    url: unknown