#
# APPLICATION.PROPERTIES
# Embedded HSQLDB without COGNOS
#

server:
  contextPath: /capitalreporting
spring:
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    platform: hsqldb
    url: jdbc:hsqldb:file:capitalreporting.db
    username: SA
    password:
  user:
    name: admin
    password: secret
cognos:
  bi:
    url: unknown
