#
# APPLICATION.PROPERTIES
# OracleDB with COGNOS
#

server:
  contextPath: /capitalreporting
spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@9.137.251.186:1521:CRDEV
    username: CR_WEB
    password: CR_WEB
    driverClassName: oracle.jdbc.OracleDriver
  db:
    platform: oracle
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@9.137.251.186:1521:CRDEV
    username: CR_WEB
    password: CR_WEB
swagger:
  base-path: /capitalreporting
security:
  basic:
    enabled: true
    path: /api/**
  user:
    name: admin
    password: secret
cognos:
  bi:
    url: 9.137.251.185:9300/bi
